name: Sync to SwaggerHub

on:
  push:
    branches:
      - main  # Change this to the branch you want to sync (e.g., 'main', 'develop')

jobs:
  sync-to-swaggerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install SwaggerHub CLI
        run: |
          pip install swaggerhub-cli

      - name: Push changes to SwaggerHub
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}  # Use the secret you created earlier
        run: |
          swaggerhub login --api-key $SWAGGERHUB_API_KEY
          swaggerhub update AuthenticationAPI2 1.0.0 --file ../output/swagger.ysml  