name: Sync to SwaggerHub

on:
  push:
    branches:
      - main  # Change this to the branch you want to sync (e.g., 'main', 'develop')

jobs:
  sync-to-swaggerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (>= 18.x)
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensures Node.js version 18.x or higher is used

      - name: Install SwaggerHub CLI via npm
        run: |
          npm install -g swaggerhub-cli  # Install SwaggerHub CLI globally

      - name: Verify swaggerhub-cli installation
        run: |
          swaggerhub --version  # Check if swaggerhub-cli was installed successfully

      - name: Push changes to SwaggerHub
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}  # Store your SwaggerHub API key in GitHub secrets
        run: |
          swaggerhub update AuthenticationAPI2 1.0.0 --file ../../output/swagger.yaml # Modify the path, API name, and version
