name: Sync to SwaggerHub

on:
  push:
    branches:
      - main  # Change this to the branch you want to sync (e.g., 'main', 'develop')

jobs:
  sync-to-swaggerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (>= 18.x)
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # This ensures that Node.js version 18.x is installed

      - name: Install SwaggerHub CLI via npm
        run: |
          npm install -g swaggerhub-cli  # Install SwaggerHub CLI globally

      - name: Push changes to SwaggerHub
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}  # Use the secret you created earlier
        run: |
          swaggerhub login --api-key $SWAGGERHUB_API_KEY
          swaggerhub update <your-api-name> <your-version> --file ./path-to-your-api-definition.yaml  # Modify the path, API name, and version
