name: Update SwaggerHub API

on:
  push:
    branches:
      - main  # Adjust to your default branch if needed

jobs:
  update-swaggerhub:
    runs-on: ubuntu-latest  # GitHub-hosted Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure compatibility with SwaggerHub CLI

      # Install SwaggerHub CLI locally
      - name: Install SwaggerHub CLI
        run: npm install swaggerhub-cli

      # Verify SwaggerHub CLI installation
      - name: Verify SwaggerHub CLI installation
        run: npx swaggerhub --version

      # Export SwaggerHub credentials to environment variables
      - name: Set up SwaggerHub environment variables
        run: |
          echo "SWAGGERHUB_URL=https://api.swaggerhub.com" >> $GITHUB_ENV
          echo "SWAGGERHUB_API_KEY=${{ secrets.SWAGGERHUB_API_KEY }}" >> $GITHUB_ENV

      # Run the SwaggerHub API update command
      - name: Update SwaggerHub API
        run: |
          npx swaggerhub api:update marutitechlabs-69b/AuthenticationAPI2/1.0.0 --file output/swagger.yaml
