name: Update SwaggerHub API

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., 'master' or 'develop')

jobs:
  update-swaggerhub:
    runs-on: ubuntu-latest  # Use GitHub's hosted Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment to install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can use any Node.js version that's compatible with SwaggerHub CLI

      # Install SwaggerHub CLI globally
      - name: Install SwaggerHub CLI
        run: |
          npm install -g swaggerhub

      # Configure SwaggerHub CLI non-interactively (using environment variables)
      - name: Configure SwaggerHub CLI
        run: |
          swaggerhub configure --url https://api.swaggerhub.com --api-key ${{ secrets.SWAGGERHUB_API_KEY }}
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}

      # Run the SwaggerHub API update command
      - name: Update SwaggerHub API
        run: |
          swaggerhub api:update marutitechlabs-69b/AuthenticationAPI2/1.0.0 --file ../../output/swagger.yaml
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
